categories_dict = {'Бытовая техника': {'main_url': '/catalogue/bytovaya-tehnika/',
                     'sub_url': (('Бытовая техника для ванной',
                                  '/catalogue/bytovaya-tehnika-dlya-vannoy/'),
                                 ('Техника для красоты',
                                  '/catalogue/krasota-i-zdorove/'),
                                 ('Техника для дома',
                                  '/catalogue/tehnika-dlya-doma/'))},
 'Водоснабжение': {'main_url': '/catalogue/vodosnabzhenie/',
                   'sub_url': (('Трубопровод', '/catalogue/truboprovod/'),
                               ('Насосы', '/catalogue/nasosy/'),
                               ('Предохранительная арматура',
                                '/catalogue/predohranitelnaya-armatura/'),
                               ('Запорно-регулирующая арматура',
                                '/catalogue/zapornaya-armatura/'),
                               ('Фильтры для коттеджей',
                                '/catalogue/kottedzhnye-sistemy-ochistki-vody/'),
                               ('Магистральные фильтры для воды',
                                '/catalogue/magistralnye-filtry-dlya-vody/'),
                               ('Фильтры для питьевой воды',
                                '/catalogue/filtry-dlya-pitevoy-vody/'),
                               ('Системы слива', '/catalogue/sistemy-sliva/'),
                               ('Водоотведение', '/catalogue/vodootvedenie/'),
                               ('Прокладки и комплектующие',
                                '/catalogue/prokladki-i-komplektuyushchie/'),
                               ('Крепеж для монтажа труб',
                                '/catalogue/krepezh-dlya-montazha-trub/'),
                               ('Инструменты и аксессуары для труб',
                                '/catalogue/instrumenty-i-aksessuary-dlya-trub/'),
                               ('Контрольно-измерительные приборы',
                                '/catalogue/pribory-ucheta-i-izmereniy/'),
                               ('Проекты по водоснабжению и отоплению',
                                '/catalogue/proekty-po-vodosnabzheniyu-i-otopleniyu/'),
                               ('Пожарное оборудование',
                                '/catalogue/pozharnoe-oborudovanie/'))},
 'Двери': {'main_url': '/catalogue/dveri/',
           'sub_url': (('Межкомнатные двери',
                        '/catalogue/mezhkomnatnye-dveri/'),
                       ('Комплекты межкомнатных дверей',
                        '/catalogue/raspashnye-mezhkomnatnye-dveri/komplekt/'),
                       ('Дверные коробки, наличники и доборы',
                        '/catalogue/dvernye-korobki-nalichniki-i-dobory/'),
                       ('Входные металлические двери',
                        '/catalogue/metallicheskie-dveri/'),
                       ('Специальные и технические двери',
                        '/catalogue/specialnye-i-tehnicheskie-dveri/'),
                       ('Двери для бани', '/catalogue/dveri-dlya-bani/'),
                       ('Фурнитура для дверей',
                        '/catalogue/furnitura-dlya-dverey/'),
                       ('Дверные ручки', '/catalogue/ruchki-dlya-dverey/'),
                       ('Замки, комплектующие и аксессуары',
                        '/catalogue/zamki-komplektuyushchie-i-aksessuary/'),
                       ('Пена монтажная', '/catalogue/pena-montazhnaya/'))},
 'Декор': {'main_url': '/catalogue/dekor/',
           'sub_url': (('Обои', '/catalogue/oboi-dlya-sten-i-potolka/'),
                       ('Декоративные обои', '/catalogue/dekorativnye-oboi/'),
                       ('Обои под покраску', '/catalogue/oboi-pod-pokrasku/'),
                       ('Фотообои', '/catalogue/fotooboi/'),
                       ('Обои по стилям', '/catalogue/oboi-po-stilyam/'),
                       ('Клей для обоев', '/catalogue/kley-dlya-oboev/'),
                       ('Декор для стен', '/catalogue/dekor-dlya-sten/'),
                       ('Зеркала', '/catalogue/zerkala/'),
                       ('Постеры', '/catalogue/postery/'),
                       ('Часы', '/catalogue/chasy-i-budilniki/'),
                       ('Декор потолка и лепнина',
                        '/catalogue/dekor-potolka-i-lepnina/'),
                       ('Потолочные плинтусы',
                        '/catalogue/potolochnye-plintusy/'),
                       ('Декоративные панели',
                        '/catalogue/dekorativnye-paneli/'),
                       ('Молдинги', '/catalogue/moldingi/'),
                       ('Панели для отделки стен',
                        '/catalogue/gipsovye-paneli/'),
                       ('Капсульные коллекции',
                        '/catalogue/kapsulnye-kollekcii/'),
                       ('Декоративная мебель',
                        '/catalogue/dekorativnaya-mebel/'),
                       ('Кофейные столики', '/catalogue/kofeynye-stoliki/'),
                       ('Пуфики', '/catalogue/myagkie-pufiki/'),
                       ('Товары для оформления интерьера',
                        '/catalogue/oformlenie-interera/'),
                       ('Ароматы для дома', '/catalogue/aromaty-dlya-doma/'),
                       ('Предметы интерьера', '/catalogue/predmety-interera/'),
                       ('Текстиль', '/catalogue/tekstil/'),
                       ('Модный интерьер', '/catalogue/modnyy-interer/'),
                       ('Товары для творчества',
                        '/catalogue/tovary-dlya-tvorchestva/'),
                       ('Праздничный декор и подарки',
                        '/catalogue/prazdnichnyy-dekor-i-podarki/'),
                       ('Декор для детской', '/catalogue/dekor-dlya-detskoy/'),
                       ('Декор для кухни', '/catalogue/dekor-dlya-kuhni/'),
                       ('Декор для спальни', '/catalogue/dekor-dlya-spalni/'),
                       ('Декор для нежилых и коммерческих помещений',
                        '/catalogue/dekor-dlya-nezhilyh-i-kommercheskih-pomeshcheniy/'))},
 'Инструменты': {'main_url': '/catalogue/instrumenty/',
                 'sub_url': (('Электроинструменты',
                              '/catalogue/elektroinstrumenty/'),
                             ('Аксессуары для электроинструмента',
                              '/catalogue/aksessuary-dlya-elektroinstrumenta/'),
                             ('Ручной инструмент',
                              '/catalogue/ruchnoy-instrument/'),
                             ('Генераторы', '/catalogue/generatory/'),
                             ('Минимойки и строительные пылесосы',
                              '/catalogue/minimoyki-i-stroitelnye-pylesosy/'),
                             ('Оборудование для мастерской',
                              '/catalogue/oborudovanie-dlya-masterskoy/'),
                             ('Электрические пилы',
                              '/catalogue/elektricheskie-pily/'),
                             ('Сварочное оборудование',
                              '/catalogue/svarochnoe-oborudovanie/'),
                             ('Станки', '/catalogue/stanki/'),
                             ('Измерительно-разметочный инструмент',
                              '/catalogue/izmeritelno-razmetochnyy-instrument/'),
                             ('Бензиновая техника',
                              '/catalogue/benzinovaya-tehnika/'),
                             ('Организация рабочего места',
                              '/catalogue/organizaciya-rabochego-mesta/'),
                             ('Фиксирующий инструмент',
                              '/catalogue/fiksiruyushchiy-instrument/'),
                             ('Штукатурно-отделочный инструмент',
                              '/catalogue/shtukaturno-otdelochnye-instrumenty/'),
                             ('Специализированный инструмент для ремонта',
                              '/catalogue/specinstrumenty-dlya-remonta/'),
                             ('Профессиональные инструменты',
                              '/catalogue/professionalnye-instrumenty-i-krepezh/'),
                             ('Автотовары', '/catalogue/avtotovary/'),
                             ('Оборудование для работ на высоте',
                              '/catalogue/oborudovanie-dlya-rabot-na-vysote/'),
                             ('Строительное оборудование',
                              '/catalogue/stroitelnoe-oborudovanie/'))},
 'Климат и вентиляция': {'main_url': '/catalogue/klimaticheskaya-tehnika-i-ventilyaciya/',
                         'sub_url': (('Кондиционеры',
                                      '/catalogue/kondicionery/'),
                                     ('Вентиляторы',
                                      '/catalogue/ventilyatory/'),
                                     ('Системы микроклимата',
                                      '/catalogue/mikroklimat/'),
                                     ('Вентиляция',
                                      '/catalogue/ventilyaciya/'))},
 'Краски': {'main_url': '/catalogue/kraski/',
            'sub_url': (('Краски для внутренних работ',
                         '/catalogue/kraski-dlya-vnutrennih-rabot/'),
                        ('Краски для наружных работ',
                         '/catalogue/kraski-dlya-naruzhnyh-rabot/'),
                        ('Эмали', '/catalogue/emali/'),
                        ('Покрытия для дерева',
                         '/catalogue/pokrytiya-dlya-dereva/'),
                        ('Инструменты для покраски',
                         '/catalogue/instrumenty-dlya-pokraski/'),
                        ('Пены, герметики и уплотнители',
                         '/catalogue/peny-germetiki-i-uplotniteli/'),
                        ('Клеи', '/catalogue/klei/'),
                        ('Стрейч-пленка, малярные и упаковочные ленты',
                         '/catalogue/malyarnye-i-upakovochnye-lenty/'),
                        ('Подготовка поверхности к покраске и штукатурке',
                         '/catalogue/podgotovka-poverhnosti-k-pokraske-i-shtukaturke/'),
                        ('Проекты по покраске',
                         '/catalogue/proekty-po-pokraske/'),
                        ('Красители для красок и штукатурок',
                         '/catalogue/kolery-dlya-kraski/'),
                        ('Эпоксидные смолы', '/catalogue/epoksidnye-smoly/'),
                        ('Растворители и очистители',
                         '/catalogue/rastvoriteli-i-ochistiteli-dlya-kraski/'),
                        ('Декоративные штукатурки',
                         '/catalogue/dekorativnye-shtukaturki/'),
                        ('Декоративные краски',
                         '/catalogue/dekorativnye-kraski/'),
                        ('Аэрозольные краски',
                         '/catalogue/aerozolnye-kraski/'))},
 'Кухни': {'main_url': '/catalogue/kuhni/',
           'sub_url': (('Бытовая техника для кухни',
                        '/catalogue/bytovaya-tehnika-dlya-kuhni/'),
                       ('Столешницы и стеновые панели',
                        '/catalogue/stoleshnicy-i-stenovye-paneli/'),
                       ('Столы и стулья', '/catalogue/stoly-i-stulya/'),
                       ('Мойки и смесители для кухни',
                        '/catalogue/moyki-i-smesiteli-dlya-kuhni/'),
                       ('Встраиваемая бытовая техника',
                        '/catalogue/vstraivaemaya-bytovaya-tehnika/'),
                       ('Мелкая бытовая техника для кухни',
                        '/catalogue/melkaya-bytovaya-tehnika/'),
                       ('Организация хранения на кухне',
                        '/catalogue/organizaciya-hraneniya-na-kuhne/'),
                       ('Кухонные аксессуары',
                        '/catalogue/kuhonnye-aksessuary/'),
                       ('Барные стойки и аксессуары',
                        '/catalogue/barnye-stoyki-i-aksessuary/'),
                       ('Посуда для приготовления блюд',
                        '/catalogue/posuda-dlya-prigotovleniya-blyud/'),
                       ('Посуда для сервировки',
                        '/catalogue/posuda-dlya-servirovki/'),
                       ('Термопосуда', '/catalogue/termoposuda/'),
                       ('Обустройство зон общественного питания',
                        '/catalogue/obustroystvo-zon-obshchestvennogo-pitaniya/'),
                       ('Диспенсеры для бутилированной воды',
                        '/catalogue/dispensery-dlya-butilirovannoy-vody/'),
                       ('Освещение на кухне',
                        '/catalogue/osveshchenie-na-kuhne/'),
                       ('Столешницы и комплектующие',
                        '/catalogue/stoleshnicy-i-komplektuyushchie/'),
                       ('Стеновые панели', '/catalogue/stenovye-paneli/'),
                       ('Бытовая химия для кухни',
                        '/catalogue/chistyashchie-sredstva/dlya-kuhni/'),
                       ('Плитка для кухни', '/catalogue/plitka-dlya-kuhni/'),
                       ('Посуда', '/catalogue/posuda/'))},
 'Мебель': {'main_url': '/catalogue/mebel-dlya-doma/',
            'sub_url': (('Шкафы', '/catalogue/shkafy/'),
                        ('Стеллажи', '/catalogue/stellazhi/'),
                        ('Мягкая мебель', '/catalogue/myagkaya-mebel/'),
                        ('Кровати', '/catalogue/krovati/'),
                        ('Столы', '/catalogue/stoly/'),
                        ('Стулья', '/catalogue/stulya/'),
                        ('Компьютерные кресла',
                         '/catalogue/kompyuternye-kresla/'),
                        ('Гардеробные системы',
                         '/catalogue/garderobnye-sistemy/'),
                        ('Модульные системы Лион',
                         '/catalogue/modulnye-sistemy-lion/'),
                        ('Комоды и тумбы', '/catalogue/komody-i-tumby/'),
                        ('Вешалки', '/catalogue/veshalki/'),
                        ('Полки и кронштейны',
                         '/catalogue/polki-i-kronshteyny/'),
                        ('Обувницы и банкетки',
                         '/catalogue/obuvnicy-i-banketki/'),
                        ('Мебельные гарнитуры',
                         '/catalogue/mebelnye-garnitury/'),
                        ('Столики', '/catalogue/stoliki/'),
                        ('Ширмы', '/catalogue/shirmy/'),
                        ('Мебель для детской',
                         '/catalogue/mebel-dlya-detskoy/'),
                        ('Домашний офис', '/catalogue/domashniy-ofis/'),
                        ('Мебель для гостиной',
                         '/catalogue/mebel-dlya-gostinoy/'),
                        ('Мебель для спальни', '/catalogue/mebel-dlya-spalni/'),
                        ('Мебель для прихожей',
                         '/catalogue/mebel-dlya-prihozhey/'),
                        ('Домашняя мебель', '/catalogue/mebel/'),
                        ('Мебель для кухни', '/catalogue/mebel-dlya-kuhni/'),
                        ('Мебель для ванной комнаты',
                         '/catalogue/mebel-dlya-vannoy-komnaty/'),
                        ('Мебельная фурнитура',
                         '/catalogue/mebelnaya-furnitura/'))},
 'Напольные покрытия': {'main_url': '/catalogue/napolnye-pokrytiya/',
                        'sub_url': (('Ламинат, линолеум, кварцвинил и другие '
                                     'напольные покрытия',
                                     '/catalogue/otdelochnye-pokrytiya-dlya-pola/'),
                                    ('Напольные плинтусы, пороги и аксессуары',
                                     '/catalogue/napolnye-plintusy-porogi-i-aksessuary/'),
                                    ('Подложка и средства для укладки '
                                     'напольных покрытий',
                                     '/catalogue/podlozhka-i-sredstva-dlya-ukladki-napolnyh-pokrytiy/'),
                                    ('Средства по уходу за напольными '
                                     'покрытиями',
                                     '/catalogue/sredstva-po-uhodu-za-napolnymi-pokrytiyami/'),
                                    ('Проекты по укладке напольных покрытий',
                                     '/catalogue/proekty-po-ukladke-napolnyh-pokrytiy/'),
                                    ('Теплые полы',
                                     '/catalogue/elektricheskie-teplye-poly/'),
                                    ('Придверные коврики',
                                     '/catalogue/pridvernye-kovriki/'))},
 'Окна': {'main_url': '/catalogue/okna/',
          'sub_url': (('Готовые окна', '/catalogue/gotovye-okna/'),
                      ('Окна на заказ', '/catalogue/okna-na-zakaz/'),
                      ('Мягкие окна', '/catalogue/myagkie-okna/'),
                      ('Подоконники', '/catalogue/podokonniki/'),
                      ('Москитные сетки и комплектующие',
                       '/catalogue/moskitnye-setki-i-komplektuyushchie/'),
                      ('Балконные двери', '/catalogue/balkonnye-dveri/'),
                      ('Товары для отделки окон',
                       '/catalogue/tovary-dlya-otdelki-okon/'),
                      ('Комплектующие для окон',
                       '/catalogue/komplektuyushchie-dlya-okon/'),
                      ('Защита на окна', '/catalogue/zashchita-na-okna/'))},
 'Освещение': {'main_url': '/catalogue/osveshchenie/',
               'sub_url': (('Освещение жилых помещений',
                            '/catalogue/osveshchenie-zhilyh-pomeshcheniy/'),
                           ('Уличные светильники',
                            '/catalogue/ulichnye-svetilniki/'),
                           ('Технические светильники',
                            '/catalogue/tehnicheskie-svetilniki/'),
                           ('Лампочки', '/catalogue/lampochki/'),
                           ('Светодиодное освещение',
                            '/catalogue/svetodiodnoe-osveshchenie/'),
                           ('Проекты освещения',
                            '/catalogue/proekty-osveshcheniya/'),
                           ('Комплектующие для светильников',
                            '/catalogue/komplektuyushchie-dlya-svetilnikov/'),
                           ('Люстры', '/catalogue/lyustry/'),
                           ('Настенно-потолочные светильники',
                            '/catalogue/nastenno-potolochnye-svetilniki/'),
                           ('Точечные светильники',
                            '/catalogue/tochechnye-svetilniki/'),
                           ('Трековые системы освещения',
                            '/catalogue/trekovye-sistemy-osveshcheniya/'),
                           ('Светодиодные панели',
                            '/catalogue/svetodiodnye-paneli/'),
                           ('Ленты светодиодные',
                            '/catalogue/lenty-svetodiodnye/'),
                           ('Прожекторы', '/catalogue/prozhektory/'),
                           ('Стилевые коллекции светильников',
                            '/catalogue/stili-svetilnikov/'),
                           ('Настенные светильники и бра',
                            '/catalogue/nastennye-svetilniki/'),
                           ('Потолочные светильники',
                            '/catalogue/svetilniki-potolochnye/'),
                           ('Светильники линейные',
                            '/catalogue/svetilniki-lineynye/'),
                           ('Светильники подвесные',
                            '/catalogue/lyustry-podvesnye/'),
                           ('Фонари ручные', '/catalogue/fonari/'))},
 'Отопительное оборудование': {'main_url': '/catalogue/otopitelnoe-oborudovanie/',
                               'sub_url': (('Радиаторы отопления',
                                            '/catalogue/radiatory-otopleniya/'),
                                           ('Обогреватели',
                                            '/catalogue/obogrevateli/'),
                                           ('Электрические теплые полы',
                                            '/catalogue/elektricheskie-teplye-poly/'),
                                           ('Водяные теплые полы',
                                            '/catalogue/teplyy-vodyanoy-pol/'),
                                           ('Отопительные котлы',
                                            '/catalogue/otopitelnye-kotly/'),
                                           ('Полотенцесушители',
                                            '/catalogue/polotencesushiteli/'),
                                           ('Тепловые пушки и нагреватели',
                                            '/catalogue/teplovye-pushki-i-nagrevateli/'),
                                           ('Греющие кабели',
                                            '/catalogue/greyushchie-kabeli/'),
                                           ('Электрический обогрев дома и '
                                            'квартиры',
                                            '/catalogue/elektricheskiy-obogrev-doma-i-kvartiry/'),
                                           ('Печи и камины',
                                            '/catalogue/pechi-i-kaminy/'))},
 'Плитка': {'main_url': '/catalogue/plitka/',
            'sub_url': (('Плитка, керамогранит и мозаика',
                         '/catalogue/plitka-keramogranit-i-mozaika/'),
                        ('Затирки для швов плитки',
                         '/catalogue/zatirki-dlya-shvov-plitki/'),
                        ('Клеи и средства для укладки плитки',
                         '/catalogue/klei-i-sredstva-dlya-ukladki-plitki/'),
                        ('Инструменты для плиточных работ',
                         '/catalogue/instrumenty-dlya-plitochnyh-rabot/'),
                        ('Плитка для ступеней и фасадов',
                         '/catalogue/plitka-dlya-stupeney-i-fasadov/'),
                        ('Люки под плитку', '/catalogue/lyuki-pod-plitku/'),
                        ('Плитка для коммерческих и общественных помещений',
                         '/catalogue/plitka-dlya-kommercheskih-i-obshchestvennyh-pomeshcheniy/'),
                        ('ПВХ-плитка', '/catalogue/pvh-plitka/'),
                        ('Отделка и обновление крыльца',
                         '/catalogue/otdelka-i-obnovlenie-krylca/'),
                        ('Услуга Укладка плитки',
                         '/uslugi/catalogue/ukladka-plitki/'))},
 'Сад': {'main_url': '/catalogue/sad/',
         'sub_url': (('Сейчас в сезоне', '/catalogue/seychas-v-sezone/'),
                     ('Товары для уборки снега',
                      '/catalogue/tovary-dlya-uborki-snega/'),
                     ('Садовая техника', '/catalogue/sadovaya-tehnika/'),
                     ('Садовая мебель', '/catalogue/sadovaya-mebel/'),
                     ('Садовый инвентарь', '/catalogue/sadovyy-inventar/'),
                     ('Выращивание рассады',
                      '/catalogue/vyrashchivanie-rassady/'),
                     ('Уход за растениями', '/catalogue/uhod-za-rasteniyami/'),
                     ('Комнатные растения и цветы',
                      '/catalogue/komnatnye-rasteniya-i-cvety/'),
                     ('Барбекю для дачи', '/catalogue/barbekyu-dlya-dachi/'),
                     ('Горшки и подставки для растений',
                      '/catalogue/gorshki-i-podstavki-dlya-rasteniy/'),
                     ('Обустройство сада и огорода',
                      '/catalogue/obustroystvo-sada-i-ogoroda/'),
                     ('Товары для консервирования и виноделия',
                      '/catalogue/tovary-dlya-konservirovaniya-i-vinodeliya/'),
                     ('Средства защиты от насекомых и грызунов',
                      '/catalogue/sredstva-zashchity-ot-nasekomyh-i-gryzunov/'),
                     ('Насосы для дома и дачи',
                      '/catalogue/nasosy-dlya-doma-i-dachi/'),
                     ('Бассейны для дачи', '/catalogue/basseyny-dlya-dachi/'),
                     ('Саженцы и рассада', '/catalogue/sazhency-i-rassada/'),
                     ('Товары для полива', '/catalogue/tovary-dlya-poliva/'),
                     ('Семена', '/catalogue/semena/'),
                     ('Дачная сантехника', '/catalogue/dachnaya-santehnika/'),
                     ('Защита при работе в саду и огороде',
                      '/catalogue/zashchita-pri-rabote-v-sadu-i-ogorode/'),
                     ('Садовая обувь', '/catalogue/sadovaya-obuv/'),
                     ('Садовый декор', '/catalogue/sadovyy-dekor/'),
                     ('Детские товары для игр и отдыха',
                      '/catalogue/detskie-tovary-dlya-igr-i-otdyha/'),
                     ('Товары для туризма и активного отдыха',
                      '/catalogue/tovary-dlya-turizma-i-aktivnogo-otdyha/'),
                     ('Спортивные товары', '/catalogue/sportivnye-tovary/'),
                     ('Запчасти, аксессуары для садовой техники',
                      '/catalogue/zapchasti-i-aksessuary-dlya-sadovoy-tehniki/'),
                     ('Заборы', '/catalogue/zabory/'),
                     ('Проекты для дачного участка',
                      '/catalogue/proekty-dlya-dachnogo-uchastka/'))},
 'Сантехника': {'main_url': '/catalogue/santehnika/',
                'sub_url': (('Смесители для ванной комнаты',
                             '/catalogue/smesiteli-dlya-vannoy-komnaty/'),
                            ('Унитазы и биде', '/catalogue/unitazy-i-bide/'),
                            ('Ванны и комплектующие',
                             '/catalogue/vanny-i-komplektuyushchie/'),
                            ('Душевое оборудование',
                             '/catalogue/dushevoe-oborudovanie/'),
                            ('Раковины',
                             '/catalogue/rakoviny-v-vannuyu-komnatu/'),
                            ('Душевые кабины и ширмы',
                             '/catalogue/dushevye-kabiny-i-shirmy/'),
                            ('Зеркала и полки в ванную',
                             '/catalogue/zerkala-i-polki-v-vannuyu/'),
                            ('Хранение в ванной',
                             '/catalogue/hranenie-v-vannoy/'),
                            ('Аксессуары для ванной комнаты',
                             '/catalogue/aksessuary-dlya-vannoy-komnaty/'),
                            ('Сушилки и гладильные доски',
                             '/catalogue/sushilki-i-gladilnye-doski/'),
                            ('Детские товары для ванной',
                             '/catalogue/detskie-tovary-dlya-vannoy/'),
                            ('Биотуалеты и аксессуары',
                             '/catalogue/biotualety-i-aksessuary/'),
                            ('Товары для бани и сауны',
                             '/catalogue/banya-i-sauna/'),
                            ('Водонагреватели', '/catalogue/vodonagrevateli/'),
                            ('Двери для ванной комнаты',
                             '/catalogue/mezhkomnatnye-dveri-po-tipam-pomeshcheniya/dlya-vannoy-komnaty/'),
                            ('Техника для красоты в подарок',
                             '/catalogue/novogodnie-podarki/tehnika-dlya-krasoty/'),
                            ('Плитка для ванной комнаты',
                             '/catalogue/plitka-dlya-vannoy-komnaty/'),
                            ('Освещение в ванной',
                             '/catalogue/osveshchenie-v-vannoy/'))},
 'Скобяные изделия': {'main_url': '/catalogue/skobyanye-izdeliya/',
                      'sub_url': (('Крепеж', '/catalogue/krepezh/'),
                                  ('Перфорированные крепежные элементы',
                                   '/catalogue/perforirovannye-krepezhnye-elementy/'),
                                  ('Специальный крепеж',
                                   '/catalogue/specialnyy-krepezh/'),
                                  ('Мебельный крепеж',
                                   '/catalogue/mebelnyy-krepezh/'),
                                  ('Такелаж', '/catalogue/takelazh/'),
                                  ('Профили и листы',
                                   '/catalogue/profili-i-listy/'),
                                  ('Товары для безопасности',
                                   '/catalogue/tovary-dlya-bezopasnosti/'),
                                  ('Фурнитура для ворот, ограждений и перил',
                                   '/catalogue/furnitura-dlya-vorot-ograzhdeniy-i-peril/'),
                                  ('Почтовые ящики и декоративные элементы для '
                                   'зданий',
                                   '/catalogue/pochtovye-yashchiki-i-dekorativnye-elementy-dlya-zdaniy/'),
                                  ('Смазочные материалы',
                                   '/catalogue/smazochnye-materialy/'),
                                  ('Профессиональный крепеж',
                                   '/catalogue/professionalnyy-krepezh/'))},
 'Спецодежда и средства защиты': {'main_url': '/catalogue/specodezhda-i-sredstva-zashchity/',
                                  'sub_url': (('Спецодежда',
                                               '/catalogue/specodezhda/'),
                                              ('Обувь рабочая',
                                               '/catalogue/obuv-rabochaya/'),
                                              ('Перчатки',
                                               '/catalogue/perchatki/'),
                                              ('Защита зрения',
                                               '/catalogue/zashchita-zreniya/'),
                                              ('Защита слуха',
                                               '/catalogue/zashchita-sluha/'),
                                              ('Защита головы',
                                               '/catalogue/zashchita-golovy/'),
                                              ('Медицинские аптечки и '
                                               'антисептики',
                                               '/catalogue/medicinskie-aptechki-i-antiseptiki/'),
                                              ('Безопасность работ',
                                               '/catalogue/bezopasnost-rabot/'),
                                              ('Респираторы и защитные маски',
                                               '/catalogue/respiratory-i-zashchitnye-maski/'))},
 'Столярные изделия': {'main_url': '/catalogue/stolyarnye-izdeliya/',
                       'sub_url': (('Древесно-плитные материалы',
                                    '/catalogue/drevesno-plitnye-materialy/'),
                                   ('Пиломатериалы',
                                    '/catalogue/pilomaterialy/'),
                                   ('Отделка деревом',
                                    '/catalogue/otdelka-derevom/'),
                                   ('Террасная доска и декинг',
                                    '/catalogue/terrasnaya-doska-i-deking/'),
                                   ('Декоративные элементы для дома',
                                    '/catalogue/dekorativnye-elementy-dlya-doma/'),
                                   ('Лестницы', '/catalogue/lestnicy/'),
                                   ('Лестничные элементы',
                                    '/catalogue/lestnichnye-elementy/'),
                                   ('Товары для зонирования помещений',
                                    '/catalogue/zonirovanie/'),
                                   ('Ограждения', '/catalogue/ograzhdeniya/'))},
 'Стройматериалы': {'main_url': '/catalogue/stroymaterialy/',
                    'sub_url': (('Товары оптом',
                                 '/catalogue/stroymaterialy-optom/'),
                                ('Сухие смеси и грунтовки',
                                 '/catalogue/suhie-smesi-i-gruntovki/'),
                                ('Листовые материалы',
                                 '/catalogue/listovye-materialy/'),
                                ('Профиль для гипсокартона и аксессуары',
                                 '/catalogue/profil-dlya-gipsokartona-i-aksessuary/'),
                                ('Строительные расходные материалы',
                                 '/catalogue/stroitelnye-rashodnye-materialy/'),
                                ('Фасадные материалы',
                                 '/catalogue/fasadnye-materialy/'),
                                ('Кровля', '/catalogue/krovlya/'),
                                ('Блоки для строительства',
                                 '/catalogue/bloki-dlya-stroitelstva/'),
                                ('Дорожные покрытия',
                                 '/catalogue/dorozhnye-pokrytiya/'),
                                ('Наружная канализация',
                                 '/catalogue/naruzhnaya-kanalizaciya/'),
                                ('Теплоизоляция',
                                 '/catalogue/teploizolyaciya/'),
                                ('Гидроизоляция',
                                 '/catalogue/gidroizolyaciya/'),
                                ('Шумоизоляция', '/catalogue/shumoizolyaciya/'),
                                ('Ветро-влагозащита и пароизоляция кровли и '
                                 'фасадов',
                                 '/catalogue/vetro-vlagozashchita-i-paroizolyaciya-krovli-i-fasadov/'),
                                ('Системы отведения воды с участка',
                                 '/catalogue/sistemy-otvedeniya-vody-s-uchastka/'),
                                ('Подвесные потолки',
                                 '/catalogue/podvesnye-potolki/'),
                                ('Металлопрокат', '/catalogue/metalloprokat/'),
                                ('Запчасти и комплектующие для промышленного '
                                 'оборудования',
                                 '/catalogue/zapchasti-i-komplektuyushchie-dlya-promyshlennogo-oborudovaniya/'))},
 'Текстиль': {'main_url': '/catalogue/tekstil/',
              'sub_url': (('Декор по стилям', '/catalogue/dekor-po-stilyam/'),
                          ('Постельные принадлежности',
                           '/catalogue/postelnye-prinadlezhnosti/'),
                          ('Постельное бельё', '/catalogue/postelnoe-bele/'),
                          ('Домашний текстиль',
                           '/catalogue/tekstil-dlya-doma/'),
                          ('Шторы', '/catalogue/oformlenie-okna/'),
                          ('Готовые шторы',
                           '/catalogue/gotovye-shtory-i-tyuli/'),
                          ('Тюль', '/catalogue/tyul/'),
                          ('Комплекты штор',
                           '/catalogue/gotovye-shtory-i-tyuli/komplekty/'),
                          ('Рулонные шторы', '/catalogue/rulonnye-shtory/'),
                          ('Римские шторы', '/catalogue/rimskie-shtory/'),
                          ('Жалюзи', '/catalogue/zhalyuzi/'),
                          ('Комплекты вертикальных жалюзи',
                           '/catalogue/vertikalnye-zhalyuzi/komplekt/'),
                          ('Пленка для окон',
                           '/catalogue/samokleyashchayasya-plenka/plenka-dlya-okon/'),
                          ('Карнизы для штор',
                           '/catalogue/karnizy-dlya-shtor/'),
                          ('Электрокарнизы', '/catalogue/elektrokarnizy/'),
                          ('Матрасы', '/catalogue/matrasy/'),
                          ('Топперы', '/catalogue/matrasy/toppery/'),
                          ('Наматрасники', '/catalogue/namatrasniki/'),
                          ('Покрывала', '/catalogue/pokryvala/'),
                          ('Пледы', '/catalogue/pledy/'),
                          ('Декоративные подушки',
                           '/catalogue/dekorativnye-podushki/'),
                          ('Сидушки на стулья',
                           '/catalogue/sidushki-na-stulya/'),
                          ('Комплекты постельного белья',
                           '/catalogue/komplekty-postelnogo-belya/'),
                          ('Простыни', '/catalogue/prostyni/'),
                          ('Наволочки', '/catalogue/navolochki/'),
                          ('Пододеяльники', '/catalogue/pododeyalniki/'),
                          ('Одеяла', '/catalogue/odeyala/'),
                          ('Подушки', '/catalogue/podushki/'),
                          ('Ткани', '/catalogue/tkan-dlya-dekora/'),
                          ('Ковры и коврики для интерьера',
                           '/catalogue/kovry-i-kovriki-dlya-interera/'),
                          ('Текстиль и штанги для ванной комнаты',
                           '/catalogue/tekstil-i-shtangi-dlya-vannoy-komnaty/'))},
 'Товары для уборки': {'main_url': '/catalogue/tovary-dlya-uborki/',
                       'sub_url': (('Инвентарь для уборки',
                                    '/catalogue/inventar-dlya-uborki/'),
                                   ('Бытовая химия',
                                    '/catalogue/bytovaya-himiya/'),
                                   ('Товары для профессионального клининга',
                                    '/catalogue/tovary-dlya-professionalnogo-klininga/'),
                                   ('Товары для личной гигиены',
                                    '/catalogue/tovary-dlya-lichnoy-gigieny/'))},
 'Хранение': {'main_url': '/catalogue/hranenie/',
              'sub_url': (('Стеллажные системы хранения',
                           '/catalogue/stellazhnye-sistemy-hraneniya/'),
                          ('Хранение в гараже и мастерской',
                           '/catalogue/hranenie-v-garazhe-i-masterskoy/'),
                          ('Аксессуары для хранения',
                           '/catalogue/aksessuary-dlya-hraneniya/'),
                          ('Мебельные детали и комплектующие',
                           '/catalogue/mebelnye-detali-i-komplektuyushchie/'),
                          ('Ёмкости для хранения',
                           '/catalogue/emkosti-dlya-hraneniya/'),
                          ('Коробки и упаковочные материалы',
                           '/catalogue/korobki-i-upakovochnye-materialy/'),
                          ('Сумки и чемоданы', '/catalogue/sumki-i-chemodany/'),
                          ('Уход за одеждой', '/catalogue/uhod-za-odezhdoy/'))},
 'Электротовары': {'main_url': '/catalogue/elektrotovary/',
                   'sub_url': (('Розетки и выключатели',
                                '/catalogue/rozetki-vyklyuchateli-i-ramki/'),
                               ('Кабель и монтаж',
                                '/catalogue/kabel-i-montazh/'),
                               ('Электрощитовое оборудование',
                                '/catalogue/elektroshchitovoe-oborudovanie/'),
                               ('Электромонтажный инструмент',
                                '/catalogue/elektromontazhnyy-instrument/'),
                               ('Удлинители и сетевые фильтры',
                                '/catalogue/udliniteli-i-setevye-filtry/'),
                               ('Дверные звонки и домофоны',
                                '/catalogue/dvernye-zvonki-i-domofony/'),
                               ('Системы безопасности и наблюдения',
                                '/catalogue/sistemy-bezopasnosti-i-nablyudeniya/'),
                               ('Сетевое оборудование и СКС',
                                '/catalogue/telekommunikacii/'),
                               ('Элементы питания и зарядные устройства',
                                '/catalogue/elementy-pitaniya-i-zaryadnye-ustroystva/'),
                               ('Фонари', '/catalogue/fonari/'),
                               ('Умный дом', '/catalogue/umnyy-dom/'),
                               ('Огнетушители', '/catalogue/ognetushiteli/'))}}

